[package]
name = "proto"
authors = ["Javi Romero <elmurci@gmail.com>"]
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
prost.workspace = true

[build-dependencies]
prost-build = "0.13.3"

