[package]
name = "proto"
authors = ["Javi Romero <elmurci@gmail.com>"]
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes = "1.7.2"
prost = "0.13.3"

[build-dependencies]
prost-build = "0.13.3"
