[package]
name = "proto"
version = "0.0.1"
authors = ["Javi Romero <elmurci@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = "1.7.2"
prost = "0.13.3"

[build-dependencies]
prost-build = "0.13.3"
