[package]
name = "consensus"
authors = ["Javi Romero <elmurci@gmail.com>"]
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]

# local
shared = { path = "../shared" }